"""empty message

Revision ID: 2a5029d1e891
Revises: 9ab2cfe2416b
Create Date: 2018-05-25 15:46:09.118981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a5029d1e891'
down_revision = '9ab2cfe2416b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chatconnection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('u_id1', sa.Integer(), nullable=True),
    sa.Column('u_id2', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chatrecord',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('chat_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['chat_id'], ['chatconnection.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chatrecord')
    op.drop_table('chatconnection')
    # ### end Alembic commands ###
