"""empty message

Revision ID: 9ab2cfe2416b
Revises: 8759ae3df004
Create Date: 2018-05-24 10:51:04.959435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ab2cfe2416b'
down_revision = '8759ae3df004'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('type', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'type')
    # ### end Alembic commands ###
