"""empty message

Revision ID: b45e3924a6fa
Revises: 86d61644f453
Create Date: 2018-05-24 10:04:28.595504

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b45e3924a6fa'
down_revision = '86d61644f453'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vote', sa.Column('sum_options', sa.Integer(), nullable=False))
    op.alter_column('vote', 'founder_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.create_foreign_key(None, 'vote', 'user', ['founder_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vote', type_='foreignkey')
    op.alter_column('vote', 'founder_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_column('vote', 'sum_options')
    # ### end Alembic commands ###
